dist: xenial
language: node_js
node_js:
  - "node"
script:
  - npm test
addons:
  chrome: stable
  firefox: latest
env:
  # Note on Linux, non-headless Chrome fails with "Chrome failed to
  # start", and non-headless Firefox fails with "can't kill an exited
  # process", so we only test headless for now.
  TACHOMETER_E2E_TEST_BROWSERS=chrome-headless,firefox-headless
